

      module PipelineGlobals
c               Use the various object definition routines
      use TiltedRingMod
      use DataCubeMod
      use BeamMod
      use ParameterVectorMod
      use SoFiACatalogueMod
      use GalaxyObjDictMode

      implicit none

      Type PipelineAnalysisFlags
        integer CoreCodeSwitch
        integer NoiseSource
        integer CenterSource
        integer ShapeSource
        integer SizeSource
        integer SysVelSource
        integer ProfileEstimateSource
        integer MomentMapsSource
        integer LikelihoodSwitch
        integer ModelTypeSwitch
        integer MinimizationSwitch
        integer VSysSource
        integer Linear_Log_SDSwitch

        integer CatFlag
      end Type




      Type(PipelineAnalysisFlags) PFlags
      Type(DataCube) ObservedDC, DataCubeMask       !Input to the code
      Type(DataCube) ModelDC                        !Generated by the code
      Type(DataCube) MaskedObservedDC
      Type(DataCube) SecondaryObservedDC
      Type(DataCube) ObservedMaps,ModelMaps,ResidualMaps
      Type(DataCube) ModelPVMaps

      real,ALLOCATABLE :: ObservedVelocityProfile(:,:)
    

      Type(TiltedRingModel) ModelTiltedRing

      Type(TiltedRingFittingOptions) TR_FittingOptions

      Type(Beam2D) ObservedBeam, SecondaryBeam

      Type(ParameterVector) PVIni,PVModel, PV_FirstFit

      Type(SoFiACat) SCatalogue, SCatLocal

      Type(GalaxyDictionary) GalaxyDict

      integer idum


      integer MomentMapSwitch   !Switch to determine how the moment maps are obtained.
                                !0==calculated from masked cube, 1==loaded from file
                                !3==constructed from diff res cube/mask combo
      integer PreAnalysisSwitch !Switch to determine mode of preanalysis preprocessing
                                !1==Get moment maps + velocity profile


      character(500) MainFolderPath, CubeletFolder,BaseName
      character(500) ObjectBaseName,DataCubeFile
      character(500) MaskName,MapNames(0:2)
      character(500) ProfileName
      character(500) CatalogueFile,OutCatName
      character(500) FittingOptionsFile

      character(500) TempCubeFile
      character(500) TempMaskFile,TempMapNames(0:2)
      character(500) SecondaryCubeFile,SecondaryMaskFile

      character(700) MainOutputFolder

      real IniGuessWidth
      real tol, ftol

      integer PID,nProcessors
      integer,parameter :: Primary=0

      integer Version

      real,parameter,dimension(2) :: VRotLims=[0.,300.]
      real,dimension(2) :: LogSDLims
      real,dimension(2) :: LinSDLims
      real,parameter,dimension(2) :: LinSDLims_MSol=[0.1,50.]


      real,parameter,dimension(2) :: SizeLims=[2.,10.]

      end module PipelineGlobals
